### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by cyj-12138** [moranbel/tdGraphEmbed#3]
Hello, I read your article and downloaded the source code to try to reproduce it. I noticed that some files in your data set cannot be read normally in pycharm, such as formula_2019_graphs_dynamic.pkl, gameofthrones_2017_graphs_dynamic.pkl and slashdot_monthly_dynamic.pkl. , I'm not sure if this is a problem with the data set I downloaded. I hope you can provide me with a new data set file. This is very important to me. Thank you very much!
In addition, I would like to ask whether there are txt files in data sets other than facebook-wall. If so, I hope you can also add it to the data set.
Thanks again!

**Comment by moranbel** [comment]
Hi

Did you try to load the pkl file like this using python code:

with open(join('data',
'game_of_thrones/gameofthrones_2017_graphs_dynamic.pkl'), 'rb') as f:
     graphs = pickle.load(f)

**Comment by cyj-12138** [comment]
Thank you very much for your answer. This is exactly the method I used. It may be that there were some problems with my computer's compiler that prevented me from opening the data set normally.
Thanks again for your answer!
